### ISSUE TITLE
It's not WORKING. 

### ISSUE THREAD

**Issue by casey1991** [filipelinhares/timenow-sublime#5]
-----------------

Traceback (most recent call last):
  File "D:\softwares\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "Timenow in C:\Users\SSZ\AppData\Roaming\Sublime Text 3\Installed Packages\Timenow.sublime-package", line 27, in run
TypeError: must be str, not None

----------------------------

**Comment by filipelinhares** [comment]
I'm working to fix it. Thanks for your feedback, @casey1991.

**Comment by filipelinhares** [comment]
Duplicated: #3
